CREATE DATABASE IF NOT EXISTS flight_booking;
USE flight_booking;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS airports (
  code VARCHAR(10) PRIMARY KEY,
  city VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  country VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS flights (
  id VARCHAR(100) PRIMARY KEY,
  flightNumber VARCHAR(20) NOT NULL,
  airlineId VARCHAR(10) NOT NULL,
  airlineName VARCHAR(100) NOT NULL,
  fromCity VARCHAR(100) NOT NULL,
  fromCode VARCHAR(10) NOT NULL,
  toCity VARCHAR(100) NOT NULL,
  toCode VARCHAR(10) NOT NULL,
  departureTime VARCHAR(10) NOT NULL,
  arrivalTime VARCHAR(10) NOT NULL,
  date VARCHAR(20) NOT NULL,
  price INT NOT NULL,
  duration VARCHAR(20) NOT NULL,
  stops INT DEFAULT 0,
  classType VARCHAR(50) NOT NULL,
  availableSeats INT NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT,
  flightId VARCHAR(100) NOT NULL,
  passengers INT NOT NULL,
  totalPrice INT NOT NULL,
  status VARCHAR(50) DEFAULT 'Confirmed',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (flightId) REFERENCES flights(id) ON DELETE CASCADE
);
